dashboard/urls.py
from django.urls import path

from dashboard.views import IndexView, ProfileView, WorkerCreateView, WorkerLoginView, ProfileEditView, TaskCreateView, \
    TaskView, TaskUpdateView, TaskDeleteView, task_mark_complete

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile"),
    path("profile/edit/<int:pk>/", ProfileEditView.as_view(), name="edit-profile"),
    path("register", WorkerCreateView.as_view(), name="register"),
    path("login", WorkerLoginView.as_view(), name="login"),
    path("task-create", TaskCreateView.as_view(), name="create-task"),
    path("task/<int:pk>/", TaskView.as_view(), name="task-view"),
    path("task/update/<int:pk>/", TaskUpdateView.as_view(), name="task-edit"),
    path("task/delete/<int:pk>/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/mark-complete/<int:pk>/", task_mark_complete, name="task-complete"),
]


app_name = "dashboard"

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("dashboard.urls", namespace="dashboard")),
]

templates/pages/index.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
  Dashboard
{% endblock %}

{% block content %}

  <div class="container-fluid py-4">
    <div class="row my-4 justify-content-center">
      <div class="col-lg-9  mb-md-0 mb-4">
        <div class="card">
          <div class="card-header pb-0">
            <div class="row">
              <div class="col-lg-6 col-7">
                <h6>My tasks</h6>
              </div>
              <div class="col-lg-6 col-5 my-auto text-end">
                <div class="dropdown float-lg-end pe-4">
                  <a class="cursor-pointer" id="dropdownTable" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-ellipsis-v text-secondary"></i>
                  </a>
                  <ul class="dropdown-menu px-2 py-3 ms-sm-n4 ms-n5" aria-labelledby="dropdownTable">
                    <li><a class="dropdown-item border-radius-md" href="{% url 'dashboard:create-task' %}">Add task</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body px-0 pb-2">
            <div class="table-responsive ">
              <table class="table align-items-center mb-0">
                <thead>
                <tr>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ">Name</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ">Description</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Members</th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Deadline</th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Completed</th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Priority</th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Type</th>
                </tr>
                </thead>
                <tbody>
                {% for task in task_list %}
                  <tr>
                    <td>
                      <div class="d-flex px-3 py-1">
                        <div class="d-flex flex-column justify-content-center">
                          <h6 class="mb-0 text-xs"><a href="{% url 'dashboard:task-view' pk=task.id %}">{{ task.name }}</a></h6>
                        </div>
                      </div>
                    </td>
                    <td>
                      <div class="d-flex px-3 py-1">
                        <div class="d-flex flex-column justify-content-center">
                          <h6 class="mb-0 text-xs">{{ task.description|truncatewords:5 }}</h6>
                        </div>
                      </div>
                    </td>
                    <td>
                      <div class=" mt-2">
                        {% for worker in task.assignees.all %}
                          {% if request.user.id == worker.id or request.user.is_superuser %}
                            <a href="{% url 'dashboard:profile' pk=worker.id %}"
                               class="avatar avatar-xs rounded-circle" data-bs-toggle="tooltip"
                               data-bs-placement="bottom" title="
                                {% if worker.first_name and worker.last_name %}{{ worker.first_name }}
                                {{ worker.last_name }}{% else %}{{ worker.username }}{% endif %}">
                              <img src="{% static 'img/person-circle.svg' %}" alt="user">
                            </a>
                          {% else %}
                            <a class="avatar avatar-xs rounded-circle" data-bs-toggle="tooltip"
                               data-bs-placement="bottom" title="
                                {% if worker.first_name and worker.last_name %}{{ worker.first_name }}
                                {{ worker.last_name }}{% else %}{{ worker.username }}{% endif %}">
                              <img src="{% static 'img/person-circle.svg' %}" alt="user">
                            </a>
                          {% endif %}
                        {% endfor %}
                      </div>
                    </td>
                    <td class="align-middle text-center text-sm">
                      <span class="text-xs font-weight-bold">{{ task.deadline }}</span>
                    </td>
                    <td class="align-middle text-center">
                      <div class="progress-wrapper w-75 mx-auto">
                        <div class="progress-info">
                          <div class="progress-percentage">
                            {% if task.is_completed %}
                              <i class="bi bi-check2-circle" style="color: green"></i>
                            {% else %}
                              <i class="bi bi-x-circle" style="color: red"></i>
                            {% endif %}
                          </div>
                        </div>
                      </div>
                    </td>
                    <td class="align-middle text-center text-sm">
                      <span class="text-xs font-weight-bold">{{ task.priority }}</span>
                    </td>
                    <td class="align-middle text-center text-sm">
                      <span class="text-xs font-weight-bold">{{ task.task_type }}</span>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      {% include "includes/footer.html" %}
    </div>
  </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block scripts %}

{% endblock scripts %}

templates/pages/profile.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
  Profile
{% endblock %}

{% block content %}

  <div class="container-fluid">
    <div class="page-header min-height-300 border-radius-xl mt-4"
         style="background-image: url('{% static 'img/curved-images/curved0.jpg' %}'); background-position-y: 50%;">
      <span class="mask bg-gradient-primary opacity-6"></span>
    </div>
    <div class="card card-body blur shadow-blur mx-4 mt-n6 overflow-hidden">
      <div class="row gx-4">
        <div class="col-auto">
          <div class="avatar avatar-xl position-relative">
            <img src="{% static 'img/person-square.svg' %}" alt="profile_image"
                 class="w-100 border-radius-lg shadow-sm">
          </div>
        </div>
        <div class="col-auto my-auto">
          <div class="h-100">
            <h5 class="mb-1">
              {% if worker.first_name and worker.last_name %}
                {{ worker.first_name }} {{ worker.last_name }}
              {% else %}
                {{ worker.username }}
              {% endif %}
            </h5>
            <p class="mb-0 font-weight-bold text-sm">
              {{ worker.position }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid py-4">
    <div class="row">
      <div class="col-12 col-xl-4">
        <div class="card h-100">
          <div class="card-header pb-0 p-3">
            <div class="row">
              <div class="col-md-8 d-flex align-items-center">
                <h6 class="mb-0">Profile Information</h6>
              </div>
              <div class="col-md-4 text-end">
                <a href="{% url 'dashboard:edit-profile' pk=worker.pk %}">
                  <i class="fas fa-user-edit text-secondary text-sm" data-bs-toggle="tooltip" data-bs-placement="top"
                     title="Edit Profile"></i>
                </a>
              </div>
            </div>
          </div>
          <div class="card-body p-3">
            <hr class="horizontal gray-light my-4">
            <ul class="list-group">
              {% if mode == "edit" %}
                <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong
                    class="text-dark">Username:</strong> {{ worker.username }}</li>
                <form role="form" method="post" action="#">
                  {% csrf_token %}
                  {% for field in form %}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    <div class="mb-3">
                      {{ field }}
                    </div>
                    <span class="text-danger">{{ field.errors }}</span>
                  {% endfor %}
                  <div class="text-center">
                    <button type="submit" class="btn bg-gradient-info w-45 mt-4 mb-0">Save profile</button>
                    <a href="{% url 'dashboard:profile' pk=worker.id %}"
                       class="btn bg-gradient-secondary w-45 mt-4 mb-0">Cancel</a>
                  </div>
                </form>
              {% else %}
                <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong
                    class="text-dark">Username:</strong> {{ worker.username }}</li>
                <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong class="text-dark">Full
                  Name:</strong> {{ worker.first_name }} {{ worker.last_name }}</li>
                <li class="list-group-item border-0 ps-0 text-sm"><strong
                    class="text-dark">Email:</strong> {{ worker.email }}</li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
      <div class="col-12 mt-4">
        <div class="card mb-4">
          <div class="card-header pb-0 p-3">
            <h6 class="mb-1">Tasks</h6>
          </div>
          <div class="card-body p-3">
            <div class="row">
              {% for task in tasks %}
                <div class="col-xl-3 col-md-6 mb-4">
                  <div class="card card-blog card-plain border">
                    <div class="card-body px-1 ">
                      <h5><a href="{% url 'dashboard:task-view' pk=task.id %}">{{ task.name }}</a></h5>
                      <p class="mb-4 text-sm">
                        {{ task.description }}
                      </p>
                      Completed:
                      {% if task.is_completed %}
                        <i class="bi bi-check2-circle" style="color: green"></i>
                      {% else %}
                        <i class="bi bi-x-circle" style="color: red"></i>
                      {% endif %}
                      <div class="d-flex align-items-center justify-content-between">
                        Deadline: {{ task.deadline }}
                      </div>
                      <div class=" mt-2">
                        Members:
                        {% for worker in task.assignees.all %}
                          {% if request.user.id == worker.id or request.user.is_superuser %}
                            <a href="{% url 'dashboard:profile' pk=worker.id %}"
                               class="avatar avatar-xs rounded-circle" data-bs-toggle="tooltip"
                               data-bs-placement="bottom" title="
                                {% if worker.first_name and worker.last_name %}{{ worker.first_name }}
                                {{ worker.last_name }}{% else %}{{ worker.username }}{% endif %}">
                              <img src="{% static 'img/person-circle.svg' %}" alt="user">
                            </a>
                          {% else %}
                            <a class="avatar avatar-xs rounded-circle" data-bs-toggle="tooltip"
                               data-bs-placement="bottom" title="
                                {% if worker.first_name and worker.last_name %}{{ worker.first_name }}
                                {{ worker.last_name }}{% else %}{{ worker.username }}{% endif %}">
                              <img src="{% static 'img/person-circle.svg' %}" alt="user">
                            </a>
                          {% endif %}
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>

    {% include "includes/footer.html" %}

  </div>

{% endblock content %}

templates/pages/task.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
{{ task.name }}
{% endblock %}

{% block content %}

  <div class="container-fluid py-4">
    <div class="row my-4 justify-content-center">
      <div class="col-lg-3 mb-md-0 mb-4">
        <div class="card h-100">
          <div class="card-header pb-0 p-3">
            <div class="row">
              <div class="col-lg-6 col-7">
                <h6>Task - {{ task.name }}</h6>
              </div>
              <div class="col-lg-6 col-5 text-end">
                  <div class="dropdown float-lg-end pe-4">
                    <a class="cursor-pointer" id="dropdownTable" data-bs-toggle="dropdown" aria-expanded="false">
                      <i class="fa fa-ellipsis-v text-secondary"></i>
                    </a>
                    <ul class="dropdown-menu px-2 py-3 ms-sm-n4 ms-n5" aria-labelledby="dropdownTable">
                      <li><a class="dropdown-item border-radius-md" href="{% url 'dashboard:task-edit' pk=task.id %}">Edit task</a></li>
                      <li><a class="dropdown-item border-radius-md" href="{% url 'dashboard:task-delete' pk=task.id %}">Delete task</a></li>
                    </ul>
                  </div>
                </div>
            </div>
          </div>
              <div class="card-body p-3">
                <hr class="horizontal gray-light">
                <ul class="list-group">
                  {% if mode == "edit" %}
                    <form role="form" method="post" action="#">
                      {% csrf_token %}
                      {% for field in form %}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="mb-3">
                          {{ field }}
                        </div>
                        <span class="text-danger">{{ field.errors }}</span>
                      {% endfor %}
                      <div class="text-center">
                        <button type="submit" class="btn bg-gradient-info w-45 mt-4 mb-0">Save task</button>
                        <a href="{% url 'dashboard:task-view' pk=task.id %}"
                           class="btn bg-gradient-secondary w-45 mt-4 mb-0">Cancel</a>
                      </div>
                    </form>
                  {% else %}
                    <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong
                        class="text-dark">Description:</strong> {{ task.description }}</li>
                    <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong class="text-dark">
                      Deadline:</strong> {{ task.deadline }}</li>
                    <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong
                        class="text-dark">Completed:</strong>
                        {% if task.is_completed %}
                              <i class="bi bi-check2-circle" style="color: green"></i>
                            {% else %}
                              <i class="bi bi-x-circle" style="color: red"></i>
                            {% endif %}
                    </li>
                    <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong
                        class="text-dark">Priority:</strong> {{ task.priority }}</li>
                    <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong
                        class="text-dark">Type:</strong> {{ task.task_type }}</li>
                    <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong
                        class="text-dark">Members:</strong>
                        {% for worker in task.assignees.all %}
                          {% if request.user.id == worker.id or request.user.is_superuser %}
                            <a href="{% url 'dashboard:profile' pk=worker.id %}"
                               class="avatar avatar-xs rounded-circle" data-bs-toggle="tooltip"
                               data-bs-placement="bottom" title="
                                {% if worker.first_name and worker.last_name %}{{ worker.first_name }}
                                {{ worker.last_name }}{% else %}{{ worker.username }}{% endif %}">
                              <img src="{% static 'img/person-circle.svg' %}" alt="user">
                            </a>
                          {% else %}
                            <a class="avatar avatar-xs rounded-circle" data-bs-toggle="tooltip"
                               data-bs-placement="bottom" title="
                                {% if worker.first_name and worker.last_name %}{{ worker.first_name }}
                                {{ worker.last_name }}{% else %}{{ worker.username }}{% endif %}">
                              <img src="{% static 'img/person-circle.svg' %}" alt="user">
                            </a>
                          {% endif %}
                        {% endfor %}
                    </li>
                  {% endif %}
                  <li class="list-group-item border-0 ps-0 pt-0 text-sm">
                    {% if not task.is_completed and "task-view" in segment%}
                      <div class="text-center">
                      <a href="{% url 'dashboard:task-complete' pk=task.id %}"
                       class="btn bg-gradient-info w-45 mt-4 mb-0">Mark complete</a>
                      </div>
                    {% endif %}
                  </li>
                </ul>
              </div>
        </div>
      </div>
      {% include "includes/footer.html" %}
    </div>
  </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block scripts %}

{% endblock scripts %}

templates/pages/task_confirm_delete.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
  Delete confirmation
{% endblock %}

{% block content %}

  <div class="container-fluid py-4">
    <div class="row my-4 justify-content-center">
      <div class="col-lg-3 mb-md-0 mb-4">
        <div class="card">
          <div class="card-header pb-0">
            <div class="row">
              <div class="col-lg-6 col-7">
                <h6>Delete task - {{ task.name }}?</h6>
              </div>
            </div>
          </div>
          <div class="card-body p-3">
            <div class="table-responsive ">
              <form action="" method="post">
                {% csrf_token %}
                <div class="text-center">
                  <button type="submit" class="btn btn-danger w-45 mt-4 mb-0">Delete</button>
                  <a href="{% url 'dashboard:task-view' pk=task.id %}"
                     class="btn bg-gradient-secondary w-45 mt-4 mb-0">Cancel</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      {% include "includes/footer.html" %}
    </div>
  </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block scripts %}

{% endblock scripts %}

templates/pages/task_create.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
  Add new task
{% endblock %}

{% block content %}

  <div class="container-fluid py-4">
    <div class="row my-4 justify-content-center">
      <div class="col-lg-3 mb-md-0 mb-4">
        <div class="card">
          <div class="card-header pb-0">
            <div class="row">
              <div class="col-lg-6 col-7">
                <h6>Add new task</h6>
              </div>
            </div>
          </div>
          <div class="card-body px-4 pb-2">
            <div class="table-responsive ">
              <form role="form" method="post" action="#">
                {% csrf_token %}
                {% for field in form %}
                  <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                  <div class="mb-3">
                    {{ field }}
                  </div>
                  <span class="text-danger">{{ field.errors }}</span>
                {% endfor %}
                <div class="text-center pb-3">
                  <button type="submit" class="btn bg-gradient-info w-45 mt-4 mb-0">Save task</button>
                  <a href="{% url 'dashboard:index' %}"
                     class="btn bg-gradient-secondary w-45 mt-4 mb-0">Cancel</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      {% include "includes/footer.html" %}
    </div>
  </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block scripts %}

{% endblock scripts %}