dashboard/urls.py
from django.urls import path

from dashboard.views import IndexView, ProfileView, WorkerCreateView, WorkerLoginView, ProfileEditView, TaskCreateView, \
    TaskView, TaskUpdateView, TaskDeleteView, task_mark_complete

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile"),
    path("profile/edit/<int:pk>/", ProfileEditView.as_view(), name="edit-profile"),
    path("register", WorkerCreateView.as_view(), name="register"),
    path("login", WorkerLoginView.as_view(), name="login"),
    path("task-create", TaskCreateView.as_view(), name="create-task"),
    path("task/<int:pk>/", TaskView.as_view(), name="task-view"),
    path("task/update/<int:pk>/", TaskUpdateView.as_view(), name="task-edit"),
    path("task/delete/<int:pk>/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/mark-complete/<int:pk>/", task_mark_complete, name="task-complete"),
]


app_name = "dashboard"

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("dashboard.urls", namespace="dashboard")),
]

templates/includes/fixed-plugin.html
{% load static %}

  <div class="fixed-plugin">
    <div class="card shadow-lg ">
      <div class="card-header pb-0 pt-3 ">
        <div class="float-start">
          <h5 class="mt-3 mb-0">Configurator</h5>
        </div>
        <div class="float-end mt-4">
          <button class="btn btn-link text-dark p-0 fixed-plugin-close-button">
            <i class="fa fa-close"></i>
          </button>
        </div>
        <!-- End Toggle Button -->
      </div>
      <hr class="horizontal dark my-1">
      <div class="card-body pt-sm-3 pt-0">
        <!-- Sidebar Backgrounds -->
        <div>
          <h6 class="mb-0">Sidebar Colors</h6>
        </div>
        <a href="javascript:void(0)" class="switch-trigger background-color">
          <div class="badge-colors my-2 text-start">
            <span class="badge filter bg-gradient-primary active" data-color="primary" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-dark" data-color="dark" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-info" data-color="info" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-success" data-color="success" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-warning" data-color="warning" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-danger" data-color="danger" onclick="sidebarColor(this)"></span>
          </div>
        </a>
        <!-- Sidenav Type -->
        <div class="mt-3">
          <h6 class="mb-0">Sidenav Type</h6>
          <p class="text-sm">Choose between 2 different sidenav types.</p>
        </div>
        <div class="d-flex">
          <button class="btn bg-gradient-primary w-100 px-3 mb-2 ms-2 active" data-class="bg-transparent" onclick="sidebarType(this)">Transparent</button>
          <button class="btn bg-gradient-primary w-100 px-3 mb-2 ms-2" data-class="bg-white" onclick="sidebarType(this)">White</button>
        </div>
        <p class="text-sm d-xl-none d-block mt-2">You can change the sidenav type just on desktop view.</p>
        <!-- Navbar Fixed -->
        <div class="mt-3">
          <h6 class="mb-0">Navbar Fixed</h6>
        </div>
        <div class="form-check form-switch ps-0">
          <input class="form-check-input mt-1 ms-auto" type="checkbox" id="navbarFixed" onclick="navbarFixed(this)">
        </div>
      </div>
    </div>
  </div>

templates/includes/footer-fullscreen.html
    <footer class="footer py-5">
      <div class="container">
        <div class="row">
          <div class="col-8 mx-auto text-center mt-1">
            <p class="mb-0 text-secondary">
              &copy; <a href="https://gitlab.com/lotrikys/task-manager" class="text-muted" target="_blank">Task Manager</a> - 2023
            </p>
          </div>
        </div>
      </div>
    </footer>

templates/includes/footer.html
<footer class="footer pt-3  ">
  <div class="container-fluid">
    <div class="row justify-content-center">
        <div class="copyright text-center text-sm text-muted ">
          &copy; <a href="https://gitlab.com/lotrikys/task-manager" class="text-muted" target="_blank">Task Manager</a> - 2023
        </div>
    </div>
  </div>
</footer>

templates/includes/navigation-fullscreen.html
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg blur blur-rounded top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
    <div class="container-fluid pe-0">
      <a class="navbar-brand font-weight-bolder ms-lg-0 ms-3 " href="{% url 'dashboard:index' %}">
        Task Manager Dashboard
      </a>
      <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon mt-2">
            <span class="navbar-toggler-bar bar1"></span>
            <span class="navbar-toggler-bar bar2"></span>
            <span class="navbar-toggler-bar bar3"></span>
          </span>
      </button>
      <div class="collapse navbar-collapse" id="navigation">
        <ul class="navbar-nav mx-auto ms-xl-auto">
          
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center me-2 active" aria-current="page" href="{% url 'dashboard:index' %}">
              <i class="fa fa-chart-pie opacity-6 me-1"></i>
              Dashboard
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->

templates/includes/navigation.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" navbar-scroll="true">
  <div class="container-fluid py-1 px-3">
    <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
      <div class="ms-md-auto pe-md-3 d-flex align-items-center">
        <div class="input-group">
          {% if "dashboard" in segment %}
          <form action="" method="get">
            {{ search_form }}
          </form>
          {% endif %}
        </div>
      </div>
      <ul class="navbar-nav  justify-content-end">
        {% if request.user.is_authenticated %}
          <li class="nav-item px-3 d-flex align-items-center">
            Welcome, {% if request.user.first_name and request.user.last_name %}{{ request.user.first_name }} {{ request.user.last_name }}
            {% else %}{{ request.user.username }}
            {% endif %}
          </li>
          <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
          <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </a>
        </li>
          <li class="nav-item px-3 d-flex align-items-center">
            <a href="{% url 'logout' %}" class="nav-link text-body font-weight-bold px-0">
              <i class="fa fa-user me-sm-1"></i>
              <span class="d-sm-inline d-none">Logout</span>
            </a>
          </li>
        {% else %}
          <li class="nav-item px-3 d-flex align-items-center">
            <a href="{% url 'dashboard:login' %}" class="nav-link text-body font-weight-bold px-0">
              <i class="fa fa-user me-sm-1"></i>
              <span class="d-sm-inline d-none">Sign In</span>
            </a>
          </li>
        {% endif %}
        {% if request.user.is_superuser %}
        <li class="nav-item px-3 d-flex align-items-center">
          <a href="{% url 'admin:index' %}" class="nav-link text-body p-0">
            <i class="fa fa-cog"></i>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!-- End Navbar -->

templates/includes/scripts.html
{% load static %}

<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
<script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
<script src="{% static 'js/dark-mode-handler.js' %}"></script>